### ISSUE TITLE
Memory Leak and Incomplete Instance Destruction with Repeated /x-transfer HTTP API calls

### ISSUE THREAD

**Issue by michaeldev5** [paraspell/xcm-api#23]
When our HTTP API /x-transfer endpoint is subjected to a high volume of persistent requests, the WsProvider from the Polkadot JS API is created repeatedly, leading to memory leaks. Even after calling the .disconnect() method, the instance isn't completely destroyed.

Steps to Reproduce:

1. Trigger a substantial number of continuous requests to our HTTP API endpoint /x-transfer.
2. Observe the creation of multiple WsProvider instances.
3. Execute .disconnect() but notice that memory isn't freed as expected.

**Comment by dudo50** [comment]
Turns out, latest version containing following fix https://github.com/paraspell/xcm-api/commit/51c6edfd885133e52ffffdae80595a933365abe7 was not deployed correctly. There are no memory leaks anymore and everything works as expected.
